# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Prisma Migrate

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
  
jobs:
  install:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
    
    - name: Check for cache
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install
      run: yarn install
    - name: Rerun Install
      run: yarn install
    
  generate:

    runs-on: ubuntu-latest
    
    needs: install
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    
    - name: Install
      run: yarn install
    - name: Rerun Install
      run: yarn install

    - name: Generate Prisma Client
      run: npx prisma generate
