# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Prisma Migrate

on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Install
        run: yarn install
      - name: Rerun Install
        run: yarn install

  generate:
    runs-on: ubuntu-latest

    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Install
        run: yarn install

      - run: rm -rf node_modules/.prisma

      - name: Generate Prisma Client
        run: npx prisma generate

  migrate:
    runs-on: ubuntu-latest

    needs: Diff Migrations

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Install
        run: yarn install

      - run: rm -rf node_modules/.prisma

      - name: Deploy Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
