name: Prisma Migrations

on:
  push:
    branches:
      - main
    paths:
      - "./prisma/**"
  pull_request:
    paths:
      - "./prisma/**/*.sql"

jobs:
  install:
    name: Install Dependencies

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: yarn install

  generate:
    name: Generate Prisma

    needs: install

    steps:
      - run: npx prisma generate
