name: Deploy Server to Railway

on:
  push:
    branches: [monorepo]
  workflow_dispatch:
    branches: [monorepo]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Install packages
        run: yarn install --immutable

      - name: Generate Prisma
        run: yarn run prisma:clean

      - name: Build
        run: yarn turbo run build --filter=server

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Link Railway
        run: railway link fe1c4abf-1b43-4709-bf27-7eb68d58624a

      - name: WHOAMI
        run: railway whoami
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
